version: 2
jobs:
   build:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: npm install
       - run: CI=true npm run build --prefix client
   test:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: npm install
       - run: npm run test
   awesome:
     docker:
       - image: circleci/node:8.9
     steps:
       - checkout
       - run: echo "Continuous Integration is dope."
workflows:
  version: 2
  build-test-and-lint:
    jobs:
      - build
      - awesome
      - test:
          requires:
            - awesome